DROP DATABASE IF EXISTS Lorra;
CREATE DATABASE Lorra;

DROP TABLE IF EXISTS Lorra.account;
CREATE TABLE Lorra.account(
EMAIL VARCHAR(50) NOT NULL PRIMARY KEY,
PASS VARCHAR(50) NOT NULL,
FECHA_CREACION DATE NOT NULL
);

DROP TABLE IF EXISTS Lorra.player;
CREATE TABLE Lorra.player(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
EMAIL VARCHAR(50) NOT NULL,
VOCATION INT(2) NOT NULL,
EXPERIENCE INT(30) NOT NULL,
VELOCIDAD INT(3) NOT NULL,
SEX INT(1) NOT NULL,
HP_MAX INT(20) NOT NULL,
HP INT(20) NOT NULL,
MANA_MAX INT(20) NOT NULL,
MANA INT(20) NOT NULL,
POINTS INT(10) NOT NULL,
OUTFITS INT(2) NOT NULL,
POS VARCHAR(15) NOT NULL,
POS_X INT(4) NOT NULL,
POS_Y INT(4) NOT NULL,
POS_Z INT(4) NOT NULL,
ACCESS INT(1) NOT NULL,
FOREIGN KEY (EMAIL) REFERENCES account(EMAIL)
);

DROP TABLE IF EXISTS Lorra.skills;
CREATE TABLE Lorra.skills(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
ATACK INT(4) default 0,
DEFENCE INT(4) default 0,
MAGIC INT(4) default 0,
LUCK INT(4) default 0,
CURSE INT(4) default 0,
FOREIGN KEY (NAME) REFERENCES Lorra.player(NAME)
);

INSERT INTO account VALUES("prueba123", sha("prueba123"), "2022-06-19");
INSERT INTO player VALUES("Mau", "prueba123", 1, 1, 1, 100, 100,20,20,0,1,"100:100:1",1);
INSERT INTO skills(NAME) VALUES("Mau");



