DROP DATABASE IF EXISTS Lorra;
CREATE DATABASE Lorra;

DROP TABLE IF EXISTS Lorra.account;
CREATE TABLE Lorra.account(
EMAIL VARCHAR(50) NOT NULL PRIMARY KEY,
PASS VARCHAR(50) NOT NULL,
FECHA_CREACION DATE NOT NULL
);

