DROP DATABASE IF EXISTS Lorra;
CREATE DATABASE Lorra;

DROP TABLE IF EXISTS Lorra.account;
CREATE TABLE Lorra.account(
EMAIL VARCHAR(50) NOT NULL PRIMARY KEY,
PASS VARCHAR(50) NOT NULL,
FECHA_CREACION DATE NOT NULL
);

DROP TABLE IF EXISTS Lorra.player;
CREATE TABLE Lorra.player(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
VOCATION INT(2) NOT NULL,
EXPERIENCE INT(30) NOT NULL,
SEX INT(1) NOT NULL,
HP_MAX INT(20) NOT NULL,
HP INT(20) NOT NULL,
MANA_MAX INT(20) NOT NULL,
MANA INT(20) NOT NULL,
POINTS INT(10) NOT NULL,
OUTFITS INT(2) NOT NULL,
POSTION VARCHAR(15) NOT NULL,
ACCESS INT(1) NOT NULL
);

DROP TABLE IF EXISTS Lorra.skills;
CREATE TABLE Lorra.skills(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
ATACK INT(4) default 0,
DEFENCE INT(4) default 0,
MAGIC INT(4) default 0,
LUCK INT(4) default 0,
CURSE INT(4) default 0,
FOREIGN KEY (NAME) REFERENCES Lorra.player(NAME)
)




